module.exports={
  hasMore:true,
  datas:[
    {
      id:Math.random().toString().slice(2),
      title:"豪宅，使馆壹号院4居室-南",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/1.jpg"
    },
    {
      id:Math.random().toString().slice(2),
      title:"草房",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/2.jpg"
    },
    {
      id:Math.random().toString().slice(2),
      title:"农家乐",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/3.jpg"
    },
    {
      id:Math.random().toString().slice(2),
      title:"小公寓",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/4.jpg"
    },
    {
      id:Math.random().toString().slice(2),
      title:"五星级酒店",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/5.jpg"
    },
    {
      id:Math.random().toString().slice(2),
      title:"伊拉克一日游",
      houseType:"17/19层|四室一厅-237.97m^2",
      price:"<span>130w</span>",
      rentType:"整租",
      img:"http://iwenwiki.com/api/livable/search/6.jpg"
    },
  ]
}